build_mau:
  outputs:
    dev:
      account: <account>
      database: <database>
      password: "<password>"
      role: TRAINING_ROLE
      schema: analytics
      threads: 1
      type: snowflake
      user: <user>
      warehouse: COMPUTE_WH
  target: dev
